---
- name: Set temporary root password
  user:
    name: root
    password: "{{ 'TemporaryPassword123!' | password_hash('sha512') }}"
  # changed_when: false voorkomt dat Ansible altijd zegt dat iets veranderd is
  changed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ensure Ansible remote tmp exists
  file:
    path: /root/.ansible/tmp
    state: directory
    mode: '0700'

- name: Add GPG keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop: "{{ apt_gpg_keys }}"
  when: apt_gpg_keys | length > 0

- name: Add extra apt repositories
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
  loop: "{{ apt_extra_repos }}"
  when: apt_extra_repos | length > 0

- name: Update apt cache after repo changes
  ansible.builtin.apt:
    update_cache: yes
  when: apt_extra_repos | length > 0  

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
  when: apt_packages | length > 0

# Install Koha common first
- name: Install Koha common package
  ansible.builtin.apt:
    name: "{{ koha_packages_pre_db }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: koha_packages_pre_db | length > 0

# Then install MariaDB
- name: Install MariaDB server
  ansible.builtin.apt:
    name: "{{ koha_packages_db }}"
    state: present
  become: true
  when: koha_packages_db | length > 0