---
- name: Test playbook voor Koha droplets
  hosts: all
  become: yes  # root-rechten, indien nodig
  tasks:
    - name: Check uptime
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Toon uptime
      ansible.builtin.debug:
        var: uptime_output.stdout

    - name: Maak testbestand aan
      ansible.builtin.file:
        path: /tmp/ansible_testfile.txt
        state: touch
        owner: ansible
        group: ansible
        mode: '0644'
